# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: nocodedb
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  engine:
    build: .
    command: bash -c "alembic upgrade head && uvicorn engine.main:app --host 0.0.0.0 --port 80"
    ports: 
      - "80:80"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://admin:admin@db/nocodedb"
    