"""rename feature name

Revision ID: 205170643f11
Revises: bcfadc7bd581
Create Date: 2023-05-23 11:36:20.281306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205170643f11'
down_revision = 'bcfadc7bd581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feature', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('Feature', 'feature_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feature', sa.Column('feature_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Feature', 'name')
    # ### end Alembic commands ###
