"""on delete to null

Revision ID: 403744476b7c
Revises: 16460fcc4cb5
Create Date: 2023-04-21 17:28:22.594427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403744476b7c'
down_revision = '16460fcc4cb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('DataCleaning_formula_id_fkey', 'DataCleaning', type_='foreignkey')
    op.drop_column('DataCleaning', 'formula_id')
    op.add_column('Formula', sa.Column('cleaning_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Formula', 'DataCleaning', ['cleaning_id'], ['id'])
    op.drop_constraint('Projects_data_source_id_fkey', 'Projects', type_='foreignkey')
    op.drop_constraint('Projects_feature_engineering_id_fkey', 'Projects', type_='foreignkey')
    op.drop_constraint('Projects_model_id_fkey', 'Projects', type_='foreignkey')
    op.drop_constraint('Projects_cleaning_id_fkey', 'Projects', type_='foreignkey')
    op.create_foreign_key(None, 'Projects', 'DataSources', ['data_source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Projects', 'SelectedModel', ['model_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Projects', 'DataCleaning', ['cleaning_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Projects', 'FeatureEngineering', ['feature_engineering_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Projects', type_='foreignkey')
    op.drop_constraint(None, 'Projects', type_='foreignkey')
    op.drop_constraint(None, 'Projects', type_='foreignkey')
    op.drop_constraint(None, 'Projects', type_='foreignkey')
    op.create_foreign_key('Projects_cleaning_id_fkey', 'Projects', 'DataCleaning', ['cleaning_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Projects_model_id_fkey', 'Projects', 'SelectedModel', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Projects_feature_engineering_id_fkey', 'Projects', 'FeatureEngineering', ['feature_engineering_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Projects_data_source_id_fkey', 'Projects', 'DataSources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Formula', type_='foreignkey')
    op.drop_column('Formula', 'cleaning_id')
    op.add_column('DataCleaning', sa.Column('formula_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('DataCleaning_formula_id_fkey', 'DataCleaning', 'Formula', ['formula_id'], ['id'])
    # ### end Alembic commands ###
