"""datasource stage paths

Revision ID: 7e4d201112ea
Revises: 205170643f11
Create Date: 2023-05-27 11:36:09.137332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e4d201112ea'
down_revision = '205170643f11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SelectedModel', sa.Column('prediction_field', sa.String(), nullable=False))
    op.add_column('SelectedModel', sa.Column('config', sa.String(), nullable=False))
    statusenum = postgresql.ENUM('TRAINING', 'TRAINED', 'FAILED', 'DEPLOYED', name='statusenum')
    statusenum.create(op.get_bind())
    op.add_column('SelectedModel', sa.Column('status', statusenum, nullable=True))
    op.add_column('SelectedModel', sa.Column('evaluation', sa.String(), nullable=True))
    op.alter_column('SelectedModel', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SelectedModel', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('SelectedModel', 'evaluation')
    op.drop_column('SelectedModel', 'status')
    op.drop_column('SelectedModel', 'config')
    op.drop_column('SelectedModel', 'prediction_field')
    # ### end Alembic commands ###
