"""fix feature engineering relation

Revision ID: 9af3bbcb820c
Revises: 403744476b7c
Create Date: 2023-05-06 10:12:33.888685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af3bbcb820c'
down_revision = '403744476b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feature', sa.Column('feature_engineering_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Feature', 'FeatureEngineering', ['feature_engineering_id'], ['id'])
    op.drop_constraint('FeatureEngineering_feature_id_fkey', 'FeatureEngineering', type_='foreignkey')
    op.drop_column('FeatureEngineering', 'feature_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeatureEngineering', sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FeatureEngineering_feature_id_fkey', 'FeatureEngineering', 'Feature', ['feature_id'], ['id'])
    op.drop_constraint(None, 'Feature', type_='foreignkey')
    op.drop_column('Feature', 'feature_engineering_id')
    # ### end Alembic commands ###
