"""deployment table

Revision ID: 9c65d80b85d5
Revises: 7e4d201112ea
Create Date: 2023-06-25 09:20:10.150271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c65d80b85d5'
down_revision = '7e4d201112ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Deployment_id'), 'Deployment', ['id'], unique=False)
    op.add_column('Projects', sa.Column('deployment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Projects', 'Deployment', ['deployment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Projects', type_='foreignkey')
    op.drop_column('Projects', 'deployment_id')
    op.drop_index(op.f('ix_Deployment_id'), table_name='Deployment')
    op.drop_table('Deployment')
    # ### end Alembic commands ###
