"""db init

Revision ID: d3b862a8b24f
Revises: 
Create Date: 2023-04-01 13:54:16.913408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b862a8b24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataSources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DataSources_id'), 'DataSources', ['id'], unique=False)
    op.create_table('Feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('feature_expression', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Feature_id'), 'Feature', ['id'], unique=False)
    op.create_table('Formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_string', sa.String(), nullable=True),
    sa.Column('target_column', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Formula_id'), 'Formula', ['id'], unique=False)
    op.create_table('Organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Organizations_id'), 'Organizations', ['id'], unique=False)
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roles_id'), 'Roles', ['id'], unique=False)
    op.create_index(op.f('ix_Roles_role_name'), 'Roles', ['role_name'], unique=False)
    op.create_table('SelectedModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SelectedModel_id'), 'SelectedModel', ['id'], unique=False)
    op.create_table('DataCleaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['Formula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DataCleaning_id'), 'DataCleaning', ['id'], unique=False)
    op.create_table('FeatureEngineering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['Feature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FeatureEngineering_id'), 'FeatureEngineering', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('cleaning_id', sa.Integer(), nullable=True),
    sa.Column('feature_engineering_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleaning_id'], ['DataCleaning.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['DataSources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_engineering_id'], ['FeatureEngineering.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['SelectedModel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Projects_id'), 'Projects', ['id'], unique=False)
    op.create_table('UserToProject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['Projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserToProject_id'), 'UserToProject', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserToProject_id'), table_name='UserToProject')
    op.drop_table('UserToProject')
    op.drop_index(op.f('ix_Projects_id'), table_name='Projects')
    op.drop_table('Projects')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_FeatureEngineering_id'), table_name='FeatureEngineering')
    op.drop_table('FeatureEngineering')
    op.drop_index(op.f('ix_DataCleaning_id'), table_name='DataCleaning')
    op.drop_table('DataCleaning')
    op.drop_index(op.f('ix_SelectedModel_id'), table_name='SelectedModel')
    op.drop_table('SelectedModel')
    op.drop_index(op.f('ix_Roles_role_name'), table_name='Roles')
    op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Organizations_id'), table_name='Organizations')
    op.drop_table('Organizations')
    op.drop_index(op.f('ix_Formula_id'), table_name='Formula')
    op.drop_table('Formula')
    op.drop_index(op.f('ix_Feature_id'), table_name='Feature')
    op.drop_table('Feature')
    op.drop_index(op.f('ix_DataSources_id'), table_name='DataSources')
    op.drop_table('DataSources')
    # ### end Alembic commands ###
